/******************************************************************************
 * Name:        tuberot.c
 * Purpose:     generate the rotation table for the cube in 3D.
 * Author:      Yunhui Fu
 * Created:     2009-07-29
 * Modified by:
 * RCS-ID:      $Id: $
 * Copyright:   (c) 2009 Yunhui Fu
 * Licence:     GPL licence version 3
 ******************************************************************************/

#include <stdio.h>
#include <assert.h>
#include <string.h>

#include "cubeface.h"

void
out_mapcur2all (void)
{
    size_t i, j;
    fprintf (stdout, "/*what will do when one state converted to another state, the rotation sequence: P90,UP and P90*/\n");
    fprintf (stdout, "/*当前面为某状态时，要变到某个指定状态，需要P90,UP,P90各自多少转*/\n");
    fprintf (stdout, "static const int g_cubeface_map_cur2all[24][24][3] = {\n");
    for (i = 0; i < 24; i ++) {
        fprintf (stdout, "  {\n");
        for (j = 0; j < 24; j ++) {
            if (j % 8 == 0) {
                fprintf (stdout, "    ");
            }
            fprintf (stdout, "{%d,%d,%d},", g_cubeface_map_cur2all[i][j][0], g_cubeface_map_cur2all[i][j][1], g_cubeface_map_cur2all[i][j][2]);
            if (j % 8 == 7) {
                fprintf (stdout, "\n");
            }
        }
        fprintf (stdout, "  },\n");
    }
    fprintf (stdout, "};\n");

    fprintf (stdout, "/*当前面为某状态时，要变到某个指定状态，经过的 rotnum 是多少，该 rotnum 是指在 g_cubeface_map_cur2all[0][idx][...]的索引*/\n");
    fprintf (stdout, "/*本数组是根据g_cubeface_map_cur2all 生成的*/\n");
    fprintf (stdout, "static const int g_cubeface_rotnum_cur2all[24][24] = {\n");
    for (i = 0; i < 24; i ++) {
        fprintf (stdout, "{");
        for (j = 0; j < 24; j ++) {
            fprintf (stdout, "% 3d,", g_cubeface_rotnum_cur2all[i][j]);
        }
        fprintf (stdout, "},\n");
    }
    fprintf (stdout, "};\n");
}

#if DEBUG
void
out_rotser2rotnum (void)
{
    size_t i;
    size_t j;
    size_t k;
    size_t m;

    fprintf (stdout, "/* 各个 [0]状态 在某个变换([1]P90,[2]DOWN,[3]P90)下所达到的状态 */\n");
    fprintf (stdout, "static const int g_cubeface_dbg_rotser2rotnum[24][4][4][4] = {\n");
    for (m = 0; m < 24; m ++) {
        fprintf (stdout, "  {\n");
        for (i = 0; i < 4; i ++) {
            fprintf (stdout, "    {");
            for (j = 0; j < 4; j ++) {
                fprintf (stdout, "{");
                for (k = 0; k < 4; k ++) {
                    fprintf (stdout, "% 3d,", g_cubeface_dbg_rotser2rotnum[m][i][j][k]);
                }
                fprintf (stdout, "},");
            }
            fprintf (stdout, "},\n");
        }
        fprintf (stdout, "  },\n");
    }
    fprintf (stdout, "};\n");
}
#else
#define out_rotser2rotnum()
#endif

#if 0
void out_one_cube (FILE * fp_out, int cube[CUBE_FACE_NUM])
{
    fprintf (fp_out, "    {% 2d,% 2d,% 2d,% 2d,% 2d,% 2d},\n", cube[0], cube[1], cube[2], cube[3], cube[4], cube[5]);
}
#else
#define out_one_cube(fp_out, cube) \
    fprintf (fp_out, "    {% 2d,% 2d,% 2d,% 2d,% 2d,% 2d},\n", (int *)(cube)[0], (int *)(cube)[1], (int *)(cube)[2], (int *)(cube)[3], (int *)(cube)[4], (int *)(cube)[5])
#endif

static void
print_rottabs (FILE * fp_out)
{
    size_t i;
    size_t j;
#define DEF_CONST(name, msg) \
    (fprintf (fp_out, "#define " #name "\t0x%02x", name), \
    (((msg) && strlen(msg))?fprintf (fp_out, " /* %s */", (msg)):0), \
    fprintf (fp_out, "\n"))

    fprintf (fp_out, "/* the variable g_cubeface_rotpos and g_cubeface_rottab are generated by src/utils/cuberot.c */\n");
    fprintf (fp_out, "/* the encoding of the cube graph:\n" CUBE_GRAPH "*/\n");

    DEF_CONST(CUBE_FACE_NUM, NULL);
    DEF_CONST(CUBE_ROT_NONE, NULL);
    DEF_CONST(CUBE_ROT_UP, NULL);
    DEF_CONST(CUBE_ROT_DOWN, NULL);
    DEF_CONST(CUBE_ROT_LEFT, NULL);
    DEF_CONST(CUBE_ROT_RIGHT, NULL);
    DEF_CONST(CUBE_ROT_P90, "+90 clockwise");
    DEF_CONST(CUBE_ROT_M90, "-90 clockwise");
    DEF_CONST(CUBE_ROT_MAX, NULL);

    fprintf (fp_out, "static const int g_cubeface_rotpos[24][CUBE_FACE_NUM] = {\n");
    for (i = 0; i < 24; i ++) {
        out_one_cube (fp_out, g_cubeface_rotpos[i]);
    }
    fprintf (fp_out, "}; /* end of g_cubeface_rotpos */\n");

    fprintf (fp_out, "static const int g_cubeface_rottab[24][CUBE_ROT_MAX] = {\n");
    fprintf (fp_out, "// CUBE_ROT_NONE, CUBE_ROT_UP, CUBE_ROT_DOWN, CUBE_ROT_LEFT, CUBE_ROT_RIGHT, CUBE_ROT_P90, CUBE_ROT_M90\n");

    for (i = 0; i < 24; i ++) {
        fprintf (fp_out, "    {");
        for (j = 0; j < CUBE_ROT_MAX; j ++) {
            fprintf (fp_out, "% 3d,", g_cubeface_rottab[i][j]);
        }
        fprintf (fp_out, "},\n");
    }
    fprintf (fp_out, "}; /* end of g_cubeface_rottab */\n");
    out_mapcur2all ();
    out_rotser2rotnum ();
}

#include "tilestruct.h"
void
test (const char *fname)
{
    tssiminfo_t tsim;
    tssiminfo_init (&tsim);

    rottab_gen_default ();
    print_rottabs (stdout);

    printf ("----------------- ts_sim_load_data_xml() ...\n");
    if (ts_sim_load_data_xml (&tsim, fname) >= 0) {
        printf ("----------------- OK, after load xml file:\n");
        print_rottabs (stdout);
    }

    tssiminfo_clear (&tsim);
    exit (0);
}

int
main (int argc, char *argv[])
{
    if (argc > 1) test(argv[1]);

    rottab_gen_default ();
    print_rottabs (stdout);
    return 0;
}



